version: 2
updates:
  - package-ecosystem: npm
    versioning-strategy: lockfile-only
    directory: /
    schedule:
      interval: weekly
    commit_message:
      prefix: "chore"
      include_scope: true
    ignore:
      - dependency-name: jsii
      - dependency-name: "@jsii/*"
      - dependency-name: codemaker
